### ISSUE TITLE
inizio scrittura codice

### ISSUE THREAD

**Issue by mone27** [Sav22999/mozitaantispam_bot#1]
ci sono motivi particolari perchè non è stato ancora scritto nulla, o è semplicemente mancanza di tempo?

**Comment by Sav22999** [comment]
@mone27 Grazie del messaggio. Non era stato scritto ancora alcuna linea di codice per un motivo ben preciso:
 - Dare il tempo alla comunità di leggere l'idea ed, eventualmente, di apportare modifiche prima di iniziare a scrivere il codice.

Il progetto, tuttavia, è iniziato e puoi trovare il codice [qui](https://github.com/Sav22999/mozitaantispam_bot/blob/master/mozita_antispam.py).
