### ISSUE TITLE
Tutti i messaggi in un file

### ISSUE THREAD

**Issue by Sav22999** [Sav22999/mozitaantispam_bot#5]
Inserire tutti i messaggi (frasi) in un file "Frasi.txt" o "Frasi.json".
Quindi lo script leggerà le frasi dal file nel momento dell'esecuzione.
!! **BISOGNA PRIMA RIVOLVERE IL PROBLEMA DI VERSIONE PYTHON (3.6+)** !! 

In questo modo è più facile gestire le frasi e, inoltre, se bisogna modificare solo una frase non è necessario aggiornare il file dello script, ma solo quello delle frasi.

@Mte90 cosa ne pensi?

**Comment by Mte90** [comment]
di quali frasi stiamo parlando?
Parli delle frasi che stampa il bot? direi che mi sembra una buona soluzione per alleggerire il codice del bot.

**Comment by Sav22999** [comment]
Sì, esatto. Di quelle frasi.
Inoltre potrebbero essere facilmente tradotte, nel caso qualcuno voglia adottarlo :)

**Comment by Sav22999** [comment]
Fatto ✔️
