### ISSUE TITLE
Aggiungere commenti al codice

### ISSUE THREAD

**Issue by Sav22999** [Sav22999/mozitaantispam_bot#8]
Aggiungere i commenti al codice per renderlo più leggibile a chiunque

**Comment by Mte90** [comment]
io direi anche di riorganizzarlo e dividerlo in parti piú piccole e anche di fare altri file, stile libreria cosí il codice comune tra bot lo semplifichiamo.

**Comment by Sav22999** [comment]
C'è poco di comune. Però il "controllo evento" (ovvero quello che identifica che tipo di messaggio è stato inviato) può essere reso una liberia. E il codice si alleggerisce, certo.

**Comment by Sav22999** [comment]
Fatto ✔️
